<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WinCleaner.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Catalogs\*.json" />
  </ItemGroup>

</Project>
